services:
  snow:
    image: snow_image:latest
    container_name: snow_container
    volumes:
      - static_volume:/digital-snowboarding/static
      - media_volume:/digital-snowboarding/media
    env_file:
      - env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && uvicorn config.asgi:application --host 0.0.0.0 --port 8080 --workers 5"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_container
    image: nginx_container
    volumes:
      - static_volume:/digital-snowboarding/static
      - media_volume:/digital-snowboarding/media
    depends_on:
      - snow
    ports:
      - 80:80

volumes:
  static_volume:
  media_volume: