# Generated by Django 5.0.6 on 2024-06-03 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(11)], verbose_name='Телефон'),
        ),
    ]
