# Generated by Django 5.0.6 on 2024-06-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0003_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=213, max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
