# Generated by Django 5.0.6 on 2024-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Цена за одно место'),
            preserve_default=False,
        ),
    ]
