# Generated by Django 5.0.6 on 2024-06-13 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_seat_booked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Забронированное место', 'verbose_name_plural': 'Забронированные места'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-created_at',), 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hall',
            name='columns',
            field=models.PositiveIntegerField(verbose_name='Количество мест в каждом ряду'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='rows',
            field=models.PositiveIntegerField(verbose_name='Количество рядов'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Забронированно пользователем'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='column',
            field=models.PositiveIntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.hall', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booked_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seat', verbose_name='Забронированное место'),
        ),
    ]
