# Generated by Django 5.0.6 on 2024-06-13 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_hall_options_alter_seat_options_and_more'),
        ('main', '0012_alter_gameschedule_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.gameschedule', verbose_name='Игра'),
            preserve_default=False,
        ),
    ]
