# Generated by Django 5.0.6 on 2024-06-04 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('nationality', models.CharField(max_length=255, verbose_name='Гражданство')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('quote', models.CharField(max_length=500, verbose_name='Цитата')),
                ('photo', models.ImageField(upload_to='player_photos/', verbose_name='Фото игрока')),
                ('label_photo', models.ImageField(upload_to='player_label_photos/', verbose_name='Дополнительное фото игрока')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('logo', models.ImageField(upload_to='team_logos/', verbose_name='Логотип команды')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное название команды')),
                ('country', models.CharField(max_length=100, verbose_name='Страна команды')),
                ('captain', models.CharField(max_length=255, verbose_name='Капитан команды')),
                ('year_of_foundation', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Год основания')),
                ('interesting_fact', models.CharField(max_length=500, verbose_name='Интересный факт о команде')),
            ],
        ),
        migrations.CreateModel(
            name='InterestingFactAboutPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=255, verbose_name='Интересный факт')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Игрок')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player', verbose_name='Игрок связанный с фото')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Команда игрока'),
        ),
    ]
