# Generated by Django 5.0.6 on 2024-06-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='gameschedule',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Расписание игр'},
        ),
    ]
