# Generated by Django 5.0.6 on 2024-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_gallery_options_alter_gameschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
