# Generated by Django 5.0.6 on 2024-06-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_photo',
            field=models.ImageField(default=123, upload_to='team_photos/', verbose_name='Фото команды'),
            preserve_default=False,
        ),
    ]
