# Generated by Django 5.0.6 on 2024-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_team_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='label_team_photo',
            field=models.ImageField(default=123, upload_to='player_label_team_photos/', verbose_name='Фото игрока для страницы команды'),
            preserve_default=False,
        ),
    ]
