# Generated by Django 5.0.6 on 2024-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_label_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='Слаг'),
        ),
    ]
