# Generated by Django 5.0.6 on 2024-06-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_hall_price_per_seat'),
        ('main', '0010_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameschedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.hall', verbose_name='Место проведения'),
        ),
    ]
