# Generated by Django 5.0.6 on 2024-06-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_ticket'),
        ('main', '0011_alter_gameschedule_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameschedule',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='booking.hall', verbose_name='Место проведения'),
        ),
    ]
