# Generated by Django 5.0.6 on 2024-06-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сувенира')),
                ('image', models.ImageField(upload_to='souvenirs/', verbose_name='Фотография сувенира')),
                ('price', models.FloatField(verbose_name='Цена сувенира')),
                ('users', models.ManyToManyField(blank=True, related_name='favorite_souvenirs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, добавившие сувенир в избранное')),
            ],
            options={
                'verbose_name': 'Сувенир',
                'verbose_name_plural': 'Сувениры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('address', models.CharField(max_length=455, verbose_name='Адрес')),
                ('total_price', models.FloatField(verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('souvenirs', models.ManyToManyField(related_name='order', to='shop.souvenir', verbose_name='Заказанные сувениры')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.DeleteModel(
            name='Souvenirs',
        ),
    ]
