# Generated by Django 5.0.6 on 2024-06-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_souvenirtype_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenir',
            name='type',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='shop.souvenirtype', verbose_name='Тип сувенира'),
            preserve_default=False,
        ),
    ]
